# Generated by Django 4.2 on 2023-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0018_productreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerdetail',
            name='state',
        ),
        migrations.AddField(
            model_name='salerdetail',
            name='area',
            field=models.CharField(choices=[('Githurai', 'Githurai'), ('Kahawa', 'Kahawa'), ('Ruiru', 'Ruiru'), ('Juja', 'Juja'), ('Kasarani', 'Kasarani'), ('Thika', 'Thika'), ('Kayole', 'Kayole'), ('Eastleigh', 'Eastleigh'), ('CBD', 'CBD'), ('Westlands', 'Westlands'), ('Kibera', 'Kibera'), ('Kayole', 'Kayole')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='saler',
            field=models.CharField(default='Electrocity@admin', max_length=100),
        ),
    ]
