# Generated by Django 4.2 on 2023-04-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_remove_salerdetail_state_salerdetail_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='saler',
            field=models.CharField(default='londry@admin', max_length=100),
        ),
    ]
