# Generated by Django 4.1.7 on 2023-05-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0020_alter_orders_saler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='saler',
            field=models.CharField(default='driploft@admin', max_length=100),
        ),
    ]
