# Generated by Django 4.2 on 2023-04-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='discountsCode',
            new_name='discountCode',
        ),
    ]
