# Generated by Django 4.2 on 2023-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='state',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='area',
            field=models.CharField(choices=[('Githurai', 'Githurai'), ('Kahawa', 'Kahawa'), ('Ruiru', 'Ruiru'), ('Juja', 'Juja'), ('Kasarani', 'Kasarani'), ('Thika', 'Thika'), ('Kayole', 'Kayole'), ('Eastleigh', 'Eastleigh'), ('CBD', 'CBD'), ('Westlands', 'Westlands'), ('Kibera', 'Kibera'), ('Kayole', 'Kayole')], max_length=50, null=True),
        ),
    ]
