# Generated by Django 4.1.7 on 2023-05-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userdetail_state_userdetail_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='pincode',
        ),
    ]
